source 'https://rubygems.org/'

gem 'sinatra', require: 'sinatra/base'
gem 'activerecord'
gem 'rake'
gem 'sqlite3'
gem 'sinatra-activerecord'
gem 'faraday'
gem 'rspec'
gem 'simplecov'
gem 'rack-test'
gem 'pry'