source 'https://rubygems.org/'

gem 'pg'
gem 'activerecord'
gem 'rake'
gem 'faraday'
gem 'rspec'
gem 'simplecov'
gem 'rack'
gem 'rack-test'
gem 'pry'
gem 'shoulda-matchers'
gem 'database_cleaner-active_record'